site_name: 🌐 Building Your First API with Django and Django Rest Framework
Nav:
-Home: index.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lipemorais
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/felipedemorais_
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/felipe-de-morais/
